[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/PaulStoffregen/Audio
    Wire
    SPI
    SD
    SerialFlash
build_flags = -std=c++17 -O2

[env:native]
platform = native
build_flags =
    -std=c++17
    -DNATIVE_BUILD
    -I src
test_build_src = yes
